name: Ascii design workflow
on:
    push:
        branches:
            - main
jobs:
    Print_ascii_design:
        runs-on: ubuntu-latest
        steps:
            - name: Download the cowsay package
              run: sudo apt install cowsay -y
            
            - name: Print the ascii design
              run: cowsay -f elephant "An elephant never forgets." >> design.txt

            - name: Show the output
              run: cat design.txt

            - name: Upload the artifact 
              uses: actions/upload-artifact@v7
              with:
                name: ascii-design
                path: ./design.txt

    Show_the_ascii_design:
        needs: Print_ascii_design
        runs-on: ubuntu-latest
        steps:
            - name: Download the ascii artifact
              uses: actions/download-artifact@v8
              with:
                name: ascii-design
                path: .

            - name: check the file
              run: ls -lrth

            
