name : test-workflow
on:
    push:
        branches:
            - main
jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4

        - name: install cowsay package
          run: sudo apt install cowsay -y

        - name: check is it installed
          run: which cowsay

        - name: print the ascii art
          run: cowsay "Hello, World!"
        
